---
abstract: 'Convert Apache/CLF data to binary format'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ApacheLog-Compressor
requires:
  Date::Parse: 0
  DateTime: 0
  Encode: 0
  List::Util: 0
  Socket: 0
  URI: 0
  URI::Escape: 0
  perl: 5.008
version: 0.005
